# See https://github.com/JuliaLang/Example.jl/blob/master/.travis.yml

language: julia

os:
- linux
- osx

julia:
- 1.0   # LTS release
- 1.2   # Current stable release
- nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

env:
  global:
  - DOCUMENTER_DEBUG=true

after_success:
# push coverage results
- julia -e 'using Pkg; cd(Pkg.dir("PrettyPrinting")); include("test/coverage.jl")'

jobs:
  include:
  # deploy documentation
  - stage: "Documentation"
    os: linux
    julia: 1.0
    script:
    - julia -e 'using Pkg; cd(Pkg.dir("PrettyPrinting")); include("doc/make.jl")'
    after_success: skip
