authors = ["Kirill Simonov <xi@resolvent.net>"]
name = "PrettyPrinting"
uuid = "54e16d92-306c-5ea0-a30b-337be88ac337"
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
NarrativeTest = "9563631e-acd4-5dd8-bebb-4cf36518960d"

[targets]
test = ["Coverage", "NarrativeTest"]
